name: Validate JSON

on:
  pull_request:
    paths:
      - 'data/gameData.json'
  push:
    paths:
      - 'data/gameData.json'

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate JSON with Schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          CONFIGURATION: strict
          INPUT_SCHEMA: data/gameDataSchema.json
          INPUT_JSONS: data/gameData.json

